apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: notification-pvc-claim
  namespace: egs-eventfinder
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 500Mi

      
