apiVersion: apps/v1
kind: Deployment
metadata:
  name: notificationapi-deployment
  namespace: egs-eventfinder
  labels:
    app: notification-api
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: notification-api
  template:
    metadata:
      labels:
        app: notification-api
    spec:
      dnsConfig:
        options:
        - name: ndots
          value: "1"
      containers:
      - name: notification-api
        image: registry.deti:5000/egs-eventfinder/notification-api:v4
        resources:
          requests:
            memory: "32Mi"
            cpu: "10m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 3003

---
apiVersion: v1
kind: Service
metadata:
  name: notificationapi-service
spec:
  ports:
  - port: 3003
    protocol: TCP
    targetPort: 3003
  selector:
    app: notification-api


---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: notificationapi-k3s
  namespace: egs-eventfinder
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.ingress.kubernetes.io/frontend-entry-points: http,https
    traefik.ingress.kubernetes.io/redirect-entry-point: https
    traefik.ingress.kubernetes.io/redirect-permanent: "true"
spec:
  rules:
  - host: notification-api.deti
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: notificationapi-service
            port: 
              number: 3003
